-- ============================================
-- MAMDANI OS - DEPLOY
--
-- Push the current files to every computer in the bunker over rednet.
-- Run this on a computer that holds the repository files (right next to
-- this file). Every target computer must be running deploy/receiver.lua.
--
-- Usage:
--   deploy            deploy to ALL targets
--   deploy <role>     deploy only to the targets of that role
--   deploy targets    print the known targets
-- ============================================

local args = { ... }

local CHUNK_SIZE = 16000
local REBOOT_AFTER = true -- restart every target after a successful deploy

-- Which files EVERY target gets.
local SHARED = {
    -- library bundle - keep in sync with lib/: bunkerlib.lua loads the
    -- modules below via require(), so ALL of them must sit in the target's
    -- program folder (flat).
    { src = "lib/bunkerlib.lua",    dest = "bunkerlib.lua" },
    { src = "lib/network.lua",      dest = "network.lua" },
    { src = "lib/crypto.lua",       dest = "crypto.lua" },
    { src = "lib/status.lua",       dest = "status.lua" },
    { src = "lib/drivers.lua",      dest = "drivers.lua" },
    { src = "lib/actions.lua",      dest = "actions.lua" },
    { src = "lib/doors.lua",        dest = "doors.lua" },
    { src = "lib/monitor.lua",      dest = "monitor.lua" },
    { src = "lib/client.lua",       dest = "client.lua" },
    { src = "deploy/receiver.lua",  dest = "receiver.lua" },
}

-- Role -> the target's main program (pushed from the repo). `launcher =
-- true` additionally writes a startup.lua that starts the receiver together
-- with the main program, so the target can be updated again after a reboot.
local ROLES = {
    control     = { src = "control/startup.lua",            dest = "main.lua", launcher = true },
    entrance    = { src = "client/entrance/startup.lua",    dest = "main.lua", launcher = true },
    meroom      = { src = "client/meroom/startup.lua",      dest = "main.lua", launcher = true },
    distributor = { src = "client/distributor1/startup.lua", dest = "main.lua", launcher = true },
    keypad      = { src = "client/control/startup.lua",     dest = "main.lua", launcher = true },
    -- pocket computers: no launcher (interactive tool), the files are pushed
    -- but the pocket keeps running `remote` manually
    remote      = { src = "remote/startup.lua",             dest = "remote.lua", launcher = false },
}

-- Computer ID -> role (or list of roles). Fill this in once - you find the
-- IDs on the screens of the running receivers, with `id`, or via
-- `remote list` (the CLIENT column shows the numeric computer id).
local TARGETS = {
   [10] = "controlroom",    -- ControlRoom: the monitor panels + alarm UI
    [12] = "control",        -- Control: separate door-keypad computer (door + its monitors)
    [28] = "entrance",       -- Entrance room client
    [27] = "meroom",         -- ME-Core room client
    [24] = "distributor",    -- Distributor_1 room client
    [23] = "remote",         -- pocket computer (remote CLI)
}

local LAUNCHER = [[
-- MAMDANI OS - auto launcher (generated by deploy)
-- Runs the MAIN program together with the deploy receiver, so this
-- computer can always be updated remotely.
local arg = { ... }
parallel.waitForEach(
    function()
        if fs.exists("receiver.lua") then
            shell.run("receiver.lua")
        end
    end,
    function()
        shell.run("main.lua", unpack(arg))
    end
)
]]

local function openModem()
    for _, side in ipairs({ "back", "left", "right", "top", "bottom", "front" }) do
        if (rednet.isOpen(side) or pcall(rednet.open, side)) and rednet.isOpen(side) then
            return side
        end
    end
    for _, side in ipairs(rs.getSides()) do
        if not rednet.isOpen(side) then
            if pcall(rednet.open, side) and rednet.isOpen(side) then
                return side
            end
        end
    end
    return nil
end

local function readFile(path)
    if not fs.exists(path) then
        term.setTextColor(colors.red)
        print("MISSING: " .. path)
        term.setTextColor(colors.white)
        return nil
    end
    local f = fs.open(path, "r")
    local data = f.readAll()
    f.close()
    return data
end

local function sendFile(id, dest, data)
    local total = math.max(1, math.ceil(#data / CHUNK_SIZE))
    for i = 1, total do
        local chunk = string.sub(data, (i - 1) * CHUNK_SIZE + 1, i * CHUNK_SIZE)
        rednet.send(id, { action = "file", file = dest, index = i, total = total, chunk = chunk }, "bunker_deploy")
    end
end

local function deployRole(id, role)
    local cfg = ROLES[role]
    if not cfg then
        print("  ! unknown role: " .. role)
        return
    end
    print("-> computer " .. id .. " (" .. role .. ")")
    for _, f in ipairs(SHARED) do
        local data = readFile(f.src)
        if data then
            sendFile(id, f.dest, data)
            print("   " .. f.dest .. " (" .. #data .. " b)")
        end
    end
    local data = readFile(cfg.src)
    if data then
        sendFile(id, cfg.dest, data)
        print("   " .. cfg.dest .. " (" .. #data .. " b)")
    end
    if cfg.launcher then
        sendFile(id, "startup.lua", LAUNCHER)
        print("   startup.lua (launcher)")
    end
    if REBOOT_AFTER and id ~= os.getComputerID() then
        rednet.send(id, { action = "reboot" }, "bunker_deploy")
        print("   reboot")
    end
end

local function listTargets()
    local seen = {}
    for id, role in pairs(TARGETS) do
        local roles = type(role) == "table" and table.concat(role, ", ") or role
        print("  " .. id .. " -> " .. roles)
        seen[id] = true
    end
    if next(seen) == nil then
        print("  (no targets configured - edit TARGETS in deploy/startup.lua)")
    end
end

local function matchesRole(id, role, filter)
    if filter == nil then return true end
    if type(role) == "string" then return role == filter end
    for _, r in ipairs(role) do
        if r == filter then return true end
    end
    return false
end

if args[1] == "targets" then
    print("Known targets:")
    listTargets()
    return
end

local modem = openModem()
if not modem then
    print("No modem found!")
    return
end
print("Modem: " .. modem)

local filter = args[1]
local deployed = 0
for id, role in pairs(TARGETS) do
    if matchesRole(id, role, filter) then
        if type(role) == "table" then
            for _, r in ipairs(role) do
                deployRole(id, r)
            end
        else
            deployRole(id, role)
        end
        deployed = deployed + 1
    end
end

print("")
print("Done. Targets updated: " .. deployed)
if deployed == 0 then
    print("(no targets matched - run `deploy targets` to check the config)")
end
