-- ============================================
-- MAMDANI OS - DEPLOY
--
-- Push the current files to every computer in the bunker over rednet.
-- Run this on a computer that holds the repository files (right next to
-- this file). Every target computer must be running deploy/receiver.lua.
--
-- Usage:
--   deploy            deploy to ALL targets
--   deploy <role>     deploy only to the targets of that role
--   deploy targets    print the known targets
-- ============================================

local args = { ... }

local CHUNK_SIZE = 16000
local MAX_ATTEMPTS = 4 -- resend a file until it is acknowledged
local ACK_TIMEOUT = 2 -- seconds to wait for the file ack from the target
local SEND_GAP = 0.05 -- pause between chunks so the modem can keep up
local REBOOT_AFTER = true -- restart every target after a successful deploy

-- Which files EVERY target gets.
local SHARED = {
    -- library bundle - keep in sync with lib/: bunkerlib.lua loads the
    -- modules below via require(), so ALL of them must sit in the target's
    -- program folder (flat).
    { src = "lib/bunkerlib.lua",    dest = "bunkerlib.lua" },
    { src = "lib/network.lua",      dest = "network.lua" },
    { src = "lib/crypto.lua",       dest = "crypto.lua" },
    { src = "lib/status.lua",       dest = "status.lua" },
    { src = "lib/drivers.lua",      dest = "drivers.lua" },
    { src = "lib/actions.lua",      dest = "actions.lua" },
    { src = "lib/doors.lua",        dest = "doors.lua" },
    { src = "lib/monitor.lua",      dest = "monitor.lua" },
    { src = "lib/client.lua",       dest = "client.lua" },
    { src = "deploy/receiver.lua",  dest = "receiver.lua" },
}

-- Role -> the target's main program (pushed from the repo). `launcher =
-- true` additionally writes a startup.lua that starts the receiver together
-- with the main program, so the target can be updated again after a reboot.
local ROLES = {
    control     = { src = "control/startup.lua",            dest = "main.lua", launcher = true },
    entrance    = { src = "client/entrance/startup.lua",    dest = "main.lua", launcher = true },
    meroom      = { src = "client/meroom/startup.lua",      dest = "main.lua", launcher = true },
    distributor = { src = "client/distributor1/startup.lua", dest = "main.lua", launcher = true },
    keypad      = { src = "client/control/startup.lua",     dest = "main.lua", launcher = true },
    -- pocket computers: no launcher (interactive tool), the files are pushed
    -- but the pocket keeps running `remote` manually
    remote      = { src = "remote/startup.lua",             dest = "remote.lua", launcher = false },
}

-- Computer ID -> role (or list of roles). Fill this in once - you find the
-- IDs on the screens of the running receivers, with `id`, or via
-- `remote list` (the CLIENT column shows the numeric computer id).
local TARGETS = {
    [12] = "control",        -- control room computer (monitors + keypad screen)
    [28] = "entrance",       -- Entrance room client
    [27] = "meroom",         -- ME-Core room client
    [24] = "distributor",    -- Distributor_1 room client
    [23] = "remote",         -- pocket computer (remote CLI)
}

local LAUNCHER = [[
-- MAMDANI OS - auto launcher (generated by deploy)
-- Runs the MAIN program together with the deploy receiver, so this
-- computer can always be updated remotely.
local arg = { ... }
parallel.waitForAll(
    function()
        if fs.exists("receiver.lua") then
            shell.run("receiver.lua")
        end
    end,
    function()
        shell.run("main.lua", unpack(arg))
    end
)
]]

local function openModem()
    for _, side in ipairs({ "back", "left", "right", "top", "bottom", "front" }) do
        if (rednet.isOpen(side) or pcall(rednet.open, side)) and rednet.isOpen(side) then
            return side
        end
    end
    for _, side in ipairs(rs.getSides()) do
        if not rednet.isOpen(side) then
            if pcall(rednet.open, side) and rednet.isOpen(side) then
                return side
            end
        end
    end
    return nil
end

local function readFile(path)
    if not fs.exists(path) then
        term.setTextColor(colors.red)
        print("MISSING: " .. path)
        term.setTextColor(colors.white)
        return nil
    end
    local f = fs.open(path, "r")
    local data = f.readAll()
    f.close()
    return data
end

local function sendFile(id, dest, data)
    local total = math.max(1, math.ceil(#data / CHUNK_SIZE))
    for attempt = 1, MAX_ATTEMPTS do
        for i = 1, total do
            local chunk = string.sub(data, (i - 1) * CHUNK_SIZE + 1, i * CHUNK_SIZE)
            rednet.send(id, { action = "file", file = dest, index = i, total = total, chunk = chunk }, "bunker_deploy")
            os.sleep(SEND_GAP)
        end
        local sender, msg = rednet.receive("bunker_deploy", ACK_TIMEOUT)
        if sender == id and type(msg) == "table" and msg.action == "ack" and msg.file == dest then
            return true
        end
    end
    return false
end

local function localWrite(dest, data)
    -- self-update: copy the file directly on this computer (no network)
    local d = fs.getDir(dest)
    if d ~= "" and not fs.exists(d) then
        fs.makeDir(d)
    end
    local f = fs.open(dest, "w")
    f.write(data)
    f.close()
end

local function deployRole(id, role)
    local cfg = ROLES[role]
    if not cfg then
        print("  ! unknown role: " .. role)
        return false
    end
    local self = (id == os.getComputerID())
    print("-> computer " .. id .. " (" .. role .. (self and ", this computer" or "") .. ")")
    local ok = true
    for _, f in ipairs(SHARED) do
        local data = readFile(f.src)
        if not data then
            ok = false
        elseif self then
            localWrite(f.dest, data)
            print("   " .. f.dest .. " (local)")
        elseif sendFile(id, f.dest, data) then
            print("   " .. f.dest .. " (" .. #data .. " b)")
        else
            ok = false
            print("   FAILED: " .. f.dest)
        end
    end
    local data = readFile(cfg.src)
    if data then
        if self then
            localWrite(cfg.dest, data)
            print("   " .. cfg.dest .. " (local)")
        elseif sendFile(id, cfg.dest, data) then
            print("   " .. cfg.dest .. " (" .. #data .. " b)")
        else
            ok = false
            print("   FAILED: " .. cfg.dest)
        end
    else
        ok = false
    end
    if cfg.launcher then
        if self then
            localWrite("startup.lua", LAUNCHER)
            print("   startup.lua (launcher, local)")
        elseif sendFile(id, "startup.lua", LAUNCHER) then
            print("   startup.lua (launcher)")
        else
            ok = false
            print("   FAILED: startup.lua (launcher)")
        end
    end
    if ok and REBOOT_AFTER and not self then
        rednet.send(id, { action = "reboot" }, "bunker_deploy")
        os.sleep(0.5)
        print("   reboot")
    end
    return ok
end

local function listTargets()
    local seen = {}
    for id, role in pairs(TARGETS) do
        local roles = type(role) == "table" and table.concat(role, ", ") or role
        print("  " .. id .. " -> " .. roles)
        seen[id] = true
    end
    if next(seen) == nil then
        print("  (no targets configured - edit TARGETS in deploy/startup.lua)")
    end
end

local function matchesRole(id, role, filter)
    if filter == nil then return true end
    if type(role) == "string" then return role == filter end
    for _, r in ipairs(role) do
        if r == filter then return true end
    end
    return false
end

if args[1] == "targets" then
    print("Known targets:")
    listTargets()
    return
end

local modem = openModem()
if not modem then
    print("No modem found!")
    return
end
print("Modem: " .. modem)

local filter = args[1]
local updated, failed = 0, 0
for id, role in pairs(TARGETS) do
    if matchesRole(id, role, filter) then
        if type(role) == "table" then
            local ok = true
            for _, r in ipairs(role) do
                if not deployRole(id, r) then ok = false end
            end
            if ok then updated = updated + 1 else failed = failed + 1 end
        else
            if deployRole(id, role) then updated = updated + 1 else failed = failed + 1 end
        end
    end
end

print("")
print("Done. " .. updated .. " ok, " .. failed .. " failed.")
if updated + failed == 0 then
    print("(no targets matched - run `deploy targets` to check the config)")
end