-- ============================================
-- MAMDANI OS - HTTP INSTALLER
--
-- Downloads the repository files over HTTP from BASE_URL. Host the repo
-- somewhere reachable (GitHub raw, your own web server, ...) and run this
-- on a computer:
--
--   Admin computer (gets the whole repo layout):
--       wget run <BASE_URL>/tools/install.lua
--
--   Target computer (one-time bootstrap: only the receiver, flat):
--       wget run <BASE_URL>/tools/install.lua receiver
--
-- BASE_URL must point at the REPOSITORY ROOT, so that BASE_URL/lib/network.lua
-- etc. resolve. Example (GitHub):
--   https://raw.githubusercontent.com/<user>/BunkerSoftware/main
-- ============================================

local BASE_URL = "https://raw.githubusercontent.com/TheNick24/BunkerSoftware/dev"

-- Everything the ADMIN computer needs (repo layout, relative paths).
local ALL_FILES = {
    "lib/bunkerlib.lua",
    "lib/network.lua",
    "lib/crypto.lua",
    "lib/status.lua",
    "lib/drivers.lua",
    "lib/actions.lua",
    "lib/doors.lua",
    "lib/monitor.lua",
    "lib/gearshift.lua",
    "lib/gfx.lua",
    "lib/energy.lua",
    "lib/client.lua",
    "lib/alarmin.lua",
    "lib/alarmconfig.lua",
"controlserver/startup.lua",
    "screenserver/startup.lua",
    "client/entrance/startup.lua",
    "client/meroom/startup.lua",
    "client/distributor1/startup.lua",
    "client/energyroom/startup.lua",
    "client/control/startup.lua",
    "remote/startup.lua",
    "deploy/startup.lua",
    "deploy/receiver.lua",
    "tools/install.lua",
}

-- ============================================
-- SELF-UPDATING CLIENTS (install.lua client <role>)
--
-- Every target pulls its OWN files from BASE_URL over HTTP. Rednet is only
-- used to TRIGGER an update (`deploy refresh` -> receiver runs update.lua);
-- the actual data travels over HTTP, so uploads are fast and need no acks.
-- ============================================

-- Flat library bundle every target needs (same as SHARED in deploy/startup.lua).
local CLIENT_SHARED = {
    { rel = "lib/bunkerlib.lua", dest = "bunkerlib.lua" },
    { rel = "lib/network.lua",   dest = "network.lua" },
    { rel = "lib/crypto.lua",    dest = "crypto.lua" },
    { rel = "lib/status.lua",    dest = "status.lua" },
    { rel = "lib/drivers.lua",   dest = "drivers.lua" },
    { rel = "lib/actions.lua",   dest = "actions.lua" },
    { rel = "lib/doors.lua",     dest = "doors.lua" },
    { rel = "lib/monitor.lua",   dest = "monitor.lua" },
    { rel = "lib/gearshift.lua", dest = "gearshift.lua" },
    { rel = "lib/gfx.lua",       dest = "gfx.lua" },
    { rel = "lib/energy.lua",    dest = "energy.lua" },
    { rel = "lib/client.lua",    dest = "client.lua" },
    { rel = "lib/alarmin.lua", dest = "alarmin.lua" },
    { rel = "lib/alarmconfig.lua", dest = "alarmconfig.lua" },
}

-- Role -> main program path (mirrors ROLES in deploy/startup.lua).
local CLIENT_ROLES = {
    controlserver = "controlserver/startup.lua",
    screenserver = "screenserver/startup.lua",
    control     = "client/control/startup.lua",
    entrance    = "client/entrance/startup.lua",
    meroom      = "client/meroom/startup.lua",
    distributor = "client/distributor1/startup.lua",
    maschineroom = "client/energyroom/startup.lua",
}

-- Launcher written as startup.lua: pulls the newest files over HTTP on every
-- boot, then starts the receiver (rednet manual-update trigger) together with
-- the main program. A failed pull never blocks the main program.
local function launcherFor(role)
    return [[
-- MAMDANI OS - auto launcher (generated by `install.lua client ]] .. role .. [[`)
-- Pulls the newest files over HTTP at boot, then starts the receiver
-- (rednet update trigger) together with the main program.
local arg = { ... }
pcall(shell.run, "install.lua", "client", "]] .. role .. [[", "quiet")
if fs.exists("receiver.lua") then
    parallel.waitForAll(
        function()
            shell.run("receiver.lua")
        end,
        function()
            shell.run("main.lua", unpack(arg))
        end
    )
else
    shell.run("main.lua", unpack(arg))
end
]]
end

-- update.lua: re-pulls the newest files over HTTP, then reboots. Triggered
-- manually via rednet (`deploy refresh`).
local function updateScriptFor(role)
    return [[
-- MAMDANI OS - self-update (triggered by the rednet `update` command).
-- Pulls the newest files for this room over HTTP, then reboots.
print("Updating from GitHub ...")
pcall(shell.run, "install.lua", "client", "]] .. role .. [[", "quiet")
print("Done - rebooting.")
os.reboot()
]]
end

-- Follows redirects (http.get does not do that on its own).
local function httpGet(url, redirects)
    redirects = redirects or 0
    local res = http.get(url)
    if not res then return nil, "no response" end
    local code = res.getResponseCode()
    if code == 200 then
        local data = res.readAll()
        res.close()
        return data
    end
    if code == 301 or code == 302 or code == 303 or code == 307 or code == 308 then
        local loc = res.getResponseHeaders() and res.getResponseHeaders()["location"]
        res.close()
        if loc and redirects < 5 then
            if loc:sub(1, 1) == "/" then
                local scheme, host = url:match("^(https?://[^/]+)")
                loc = (scheme or "") .. loc
            end
            return httpGet(loc, redirects + 1)
        end
    end
    res.close()
    return nil, "HTTP " .. tostring(code)
end

local function saveLocal(localRel, data)
    local dir = fs.getDir(localRel)
    if dir ~= "" and dir ~= "." and not fs.exists(dir) then
        fs.makeDir(dir)
    end
    local f = fs.open(localRel, "w")
    f.write(data)
    f.close()
end

local function download(rel, localRel)
    localRel = localRel or rel
    local url = BASE_URL .. "/" .. rel
    local data, err = httpGet(url)
    if not data then
        term.setTextColor(colors.red)
        print("FAILED: " .. rel .. " (" .. tostring(err) .. ")")
        term.setTextColor(colors.white)
        return false
    end
    saveLocal(localRel, data)
    term.setTextColor(colors.green)
    print("saved " .. localRel .. " (" .. #data .. " b)")
    term.setTextColor(colors.white)
    return true
end

-- ============ MAIN ============
local args = { ... }
local mode = (args[1] or "all"):lower()
local quiet = mode == "quiet" or mode == "client" -- no banner for client pulls
if mode == "quiet" then mode = "all" end

if not quiet then
    term.clear()
    term.setCursorPos(1, 1)
    term.setTextColor(colors.cyan)
    print("=== MAMDANI OS - HTTP INSTALLER ===")
    term.setTextColor(colors.gray)
    print("Source: " .. BASE_URL)
    term.setTextColor(colors.white)
end

if not http then
    term.setTextColor(colors.red)
    print("HTTP API is disabled on this server/license!")
    term.setTextColor(colors.white)
    return
end

if mode == "receiver" then
    -- bootstraps the receiver FLAT into the root folder, so the command
    -- `receiver` works (deploy/startup.lua also looks for receiver.lua there)
    local ok = download("deploy/receiver.lua", "receiver.lua")
    print("")
    if ok then
        term.setTextColor(colors.yellow)
        print("Now run: receiver")
    end
    term.setTextColor(colors.white)
    return
end

if mode == "client" then
    -- self-updating target: pulls its own flat bundle over HTTP. Bootstrap
    -- once with `install.lua client <role>`, afterwards the generated
    -- startup.lua re-pulls on every boot and `deploy refresh` over rednet
    -- (or running `update`) triggers a manual refresh.
    local role = (args[2] or ""):lower()
    if not CLIENT_ROLES[role] then
        term.setTextColor(colors.red)
        print("Unknown role: '" .. role .. "'")
        term.setTextColor(colors.gray)
        for r in pairs(CLIENT_ROLES) do print("  " .. r) end
        term.setTextColor(colors.white)
        return
    end
    -- keep the installer itself current for the next boot
    local selfData = httpGet(BASE_URL .. "/tools/install.lua")
    if selfData then
        saveLocal("install.lua", selfData)
    end
    local okCount, failCount = 0, 0
    for _, f in ipairs(CLIENT_SHARED) do
        if download(f.rel, f.dest) then okCount = okCount + 1 else failCount = failCount + 1 end
    end
    for _, f in ipairs({ { "deploy/receiver.lua", "receiver.lua" }, { CLIENT_ROLES[role], "main.lua" } }) do
        if download(f[1], f[2]) then okCount = okCount + 1 else failCount = failCount + 1 end
    end
    saveLocal("startup.lua", launcherFor(role))
    saveLocal("update.lua", updateScriptFor(role))
    print("")
    if failCount == 0 then
        term.setTextColor(colors.green)
        print("Self-updating client '" .. role .. "' ready (" .. okCount .. " files).")
    else
        term.setTextColor(colors.yellow)
        print("Client '" .. role .. "': " .. okCount .. " ok, " .. failCount .. " failed.")
    end
    term.setTextColor(colors.gray)
    print("Next: reboot - or run `update` to pull now.")
    term.setTextColor(colors.white)
    return
end

-- full repo (admin computer)
local files = ALL_FILES
local okCount, failCount = 0, 0
for _, rel in ipairs(files) do
    if download(rel) then okCount = okCount + 1 else failCount = failCount + 1 end
end
print("")
if failCount == 0 then
    term.setTextColor(colors.green)
    print("Done. " .. okCount .. " files installed.")
else
    term.setTextColor(colors.yellow)
    print("Done. " .. okCount .. " ok, " .. failCount .. " failed.")
end
term.setTextColor(colors.yellow)
if not quiet then
    print("Next: run `deploy` (and set TARGETS in deploy/startup.lua).")
end
term.setTextColor(colors.white)